// Generated by typings
// Source: https://raw.githubusercontent.com/typed-typings/npm-repeat-string/17eeaf882e9c0b3822653f74a028909d3fc0c97f/index.d.ts
declare module '~repeat-string/index' {
function repeatString (str: string, num: number): string;

export = repeatString;
}
declare module 'repeat-string/index' {
import main = require('~repeat-string/index');
export = main;
}
declare module 'repeat-string' {
import main = require('~repeat-string/index');
export = main;
}
